version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "repos/**"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
