injectEnvironmentFiles:
  - .env.local?
  - .env?

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: EC29D1DC-5128-4C8A-849A-BDD0936B7F02
    npmRegistryServer: "https://npm.fontawesome.com/"
