export const MAX_REGISTRATION_QUESTIONS = 25;
export const MAX_REGISTRATION_QUESTION_TITLE_LENGTH = 200;
export const MAX_REGISTRATION_QUESTION_DESCRIPTION_LENGTH = 1000;
export const MAX_REGISTRATION_ANSWER_LENGTH = 2000;
