export const localTestTenantDomainHeader = 'x-evorto-local-test-tenant-domain';
export const trustedSsrSourceHeader = 'x-forwarded-from';
export const trustedSsrSourceValue = 'ssr';
export const trustedTenantDomainHeader = 'x-tenant-domain';

// Symbol.for keeps the server-only context slot stable across the separately
// bundled HTTP entrypoint and Angular SSR application. The capability value is
// generated by the HTTP runtime, never by shared/browser code.
export const ssrRpcCapabilityContextKey = Symbol.for(
  'evorto.ssr-rpc-capability',
);

export const attachSsrRpcCapability = <A extends object>(
  context: A,
  capability: string,
): A =>
  Object.defineProperty(context, ssrRpcCapabilityContextKey, {
    value: capability,
  });

export const readSsrRpcCapability = (context: object): string | undefined => {
  if (ssrRpcCapabilityContextKey in context) {
    const capability = context[ssrRpcCapabilityContextKey];
    if (typeof capability === 'string' && capability.length > 0)
      return capability;
  }
  return undefined;
};
